apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flask-container
        image: bindreshbabu/task-webapp:latest
        ports:
        - containerPort: 5000
